### ISSUE TITLE
Set up deployment

### ISSUE THREAD

**Issue by iiegn** [commul/fromthepage#4]
_From @iiegn on July 7, 2017 7:54_

Once #1 #2 #3 have been resolved...

set up (semi-)automated deployment - likely, with [phusion passanger](https://www.phusionpassenger.com/).

_Copied from original issue: commul/fromthepage_old#4_

**Comment by iiegn** [comment]
see http://blog.scoutapp.com/articles/2017/02/10/which-ruby-app-server-is-right-for-you for a comparison of 
 - unicorn
 - puma
 - passanger

hm, puma?

hey, @nadezdaalexandrovna do you have experience with any of these three app servers?

**Comment by iiegn** [comment]
_From @nadezdaalexandrovna on July 7, 2017 12:2_

No, I don't. 

    Le Vendredi 7 juillet 2017 12h00, egon w. stemle <notifications@github.com> a écrit :
 

 see http://blog.scoutapp.com/articles/2017/02/10/which-ruby-app-server-is-right-for-you for a comparison of   
   - unicorn
   - puma
   - passanger
hm, puma?hey, @nadezdaalexandrovna do you have experience with any of these three app servers?—

**Comment by iiegn** [comment]
[fix-subfolder](/commul/transcanno/tree/fix-subfolder) now barks on
```
Uncaught ReferenceError: TranscriptionModule is not defined
    at HTMLDocument.<anonymous> (application-b8d879da68d4aad796def4f9c0ade6a99bb2bce440cbfcab147c6550a4016247.js:formatted:7716)
```
which is a reference to 
```
,
$(document).ready(function(e) {
    var t = Object.create(TranscriptionModule);
    t.init(),
    setInterval(function() {
```
i think, there are some more absolute links in files... pls. have a look.

@nadezdaalexandrovna @kreetrapper

**Comment by nadezdaalexandrovna** [comment]
Hi Egon,
Thank you for the changes you made and for posting this bug.
I made some changes and pushed to fix-subfolder, hope they will help.

But as far as I understand we still have to figure out what to do with the files
my-medium-onmousedown-functions.js
medium-tag-styles.css
that are not compiled during deployment, but are changed when using the program. 
Maybe we will have to change the path in app/controllers/category_controller.rb line 655 and 656, where those files are modified.

**Comment by iiegn** [comment]
ok: now, i'm getting:
```
FATAL -- :
ActionView::Template::Error (SyntaxError: Invalid assignment):
    115:
    116:     .page-busy-overlay
    117:
    118:     =javascript_include_tag 'application'
    119:     =yield :javascript
    120:
    121:     javascript:
  app/views/layouts/application.html.slim:118:in `_app_views_layouts_application
_html_slim__4250471135916338823_28799720'
```

**Comment by nadezdaalexandrovna** [comment]
Could you please push the file _app_views_layouts_application_html_slim__4250471135916338823_28799720 ?

**Comment by nadezdaalexandrovna** [comment]
Egon,
I psuhed again. Can you try again please?

**Comment by iiegn** [comment]
still, there seems to be an error :(
```
D, [2017-11-28T20:07:58.071047 #451] DEBUG -- :    (23.2ms)  COMMIT
D, [2017-11-28T20:07:58.072485 #451] DEBUG -- :   PageBlock Load (0.4ms)  SELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'static' AND `page_blocks`.`view` = 'splash'
I, [2017-11-28T20:07:58.074327 #451]  INFO -- :   Rendered inline template (1.1ms)
I, [2017-11-28T20:07:58.074935 #451]  INFO -- :   Rendered inline template (0.4ms)
I, [2017-11-28T20:07:58.076529 #451]  INFO -- :   Rendered page_block/_html_block.html.erb (0.3ms)
I, [2017-11-28T20:07:58.076937 #451]  INFO -- :   Rendered page_block/_html_block.html.erb (0.2ms)
I, [2017-11-28T20:07:58.077057 #451]  INFO -- :   Rendered static/splash.html.slim within layouts/application (1.4ms)
I, [2017-11-28T20:07:58.111276 #451]  INFO -- : Completed 500 Internal Server Error in 68ms
F, [2017-11-28T20:07:58.115787 #451] FATAL -- : 
ActionView::Template::Error (SyntaxError: Invalid assignment):
    34:     script type="text/javascript" src=asset_path("undo.js")
    35:     script type="text/javascript" src=asset_path("medium.js")
    36:     script type="text/javascript" src=asset_path("medium_subclass.js")
    37:     script type="text/javascript" src=asset_path("transcription_module.js")
    38:     script type="text/javascript" src=asset_path("transcription_code.js")
    39:     script type="text/javascript" src=asset_path('my-medium-onmousedown-functions.js')
    40:     javascript:  
  app/views/layouts/application.html.slim:37:in `_app_views_layouts_application_html_slim___3668970711764875185_51920900'
@
```
...and it might be that the root cause is in the script in the `javascript:` assignment (the code itself is syntactically valid - maybe some escaping...?).

**Comment by nadezdaalexandrovna** [comment]
I'm really sorry, but I have a git problem, I can't go further. I'm sure for you it will be a matter of a minute. Can you come and help me please? I can't resolve a merge conflict. Thank you.

**Comment by nadezdaalexandrovna** [comment]
Hi Egon!
Could you please retry deploying Transc&Anno again? On my side everything works fine.
Please pay attention to use the fix-subfolder-okn and NOT the fix-subfolder branch.
Thank you.

**Comment by iiegn** [comment]
it's up'n running (and seems ok): pls. try it yourself.

**Comment by nadezdaalexandrovna** [comment]
Unfortunately some URLs don't work.
Here are some of them:
http://kommul.eurac.edu/transcanno/collection/show?collection_id=1
http://kommul.eurac.edu/transcanno/transcribe/display_page?page_id=1
http://kommul.eurac.edu/transcanno/page_version/list?page_id=1

**Comment by iiegn** [comment]
http://kommul.eurac.edu/transcanno/collection/show?collection_id=1
```
I, [2017-12-04T14:58:53.715201 #24]  INFO -- : Started GET "/transcanno/collection/show?collection_id=1" for 10.12.59.0 at 2017-12-04 14:58:53 +0000
I, [2017-12-04T14:58:53.716708 #24]  INFO -- : Processing by CollectionController#show as HTML
I, [2017-12-04T14:58:53.716758 #24]  INFO -- :   Parameters: {"collection_id"=>"1"}
D, [2017-12-04T14:58:53.718084 #24] DEBUG -- :   Collection Load (0.6ms)  SELECT  `collections`.* FROM `collections`  WHERE `collections`.`id` = 1 LIMIT 1
D, [2017-12-04T14:58:53.719212 #24] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM `interactions`
D, [2017-12-04T14:58:53.720596 #24] DEBUG -- :   User Load (0.5ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
D, [2017-12-04T14:58:53.721369 #24] DEBUG -- :    (0.3ms)  BEGIN
D, [2017-12-04T14:58:53.722635 #24] DEBUG -- :   SQL (0.5ms)  INSERT INTO `interactions` (`action`, `browser`, `collection_id`, `created_on`, `ip_address`, `params`, `session_id`, `status`, `user_id`) VALUES ('show', 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', 1, '2017-12-04 14:58:53', '10.12.59.0', '{\"collection_id\"=>\"1\", \"controller\"=>\"collection\", \"action\"=>\"show\"}', 141, 'incomplete', 2)
D, [2017-12-04T14:58:53.735108 #24] DEBUG -- :    (12.3ms)  COMMIT
D, [2017-12-04T14:58:53.736229 #24] DEBUG -- :   PageBlock Load (0.8ms)  SELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'collection' AND `page_blocks`.`view` = 'show'
D, [2017-12-04T14:58:53.737028 #24] DEBUG -- :    (0.5ms)  SELECT categories.title, categorystyles.colour, categorystyles.textdecoration, categorystyles.fontstyle, categories.id FROM `categorystyles` INNER JOIN `categories` ON `categories`.`id` = `categorystyles`.`category_id`
I, [2017-12-04T14:58:53.737416 #24]  INFO -- : Completed 500 Internal Server Error in 21ms
F, [2017-12-04T14:58:53.738831 #24] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - app/assets/javascripts/medium-tag-styles.css):
  app/controllers/category_controller.rb:657:in `write'
  app/controllers/category_controller.rb:657:in `apply_all_styles_h'
  app/controllers/collection_controller.rb:49:in `updateStylesIfCollectionIdNotInCookies'
  app/controllers/collection_controller.rb:57:in `show'
```

http://kommul.eurac.edu/transcanno/transcribe/display_page?page_id=1
```
I, [2017-12-04T14:59:19.752336 #24]  INFO -- : Started GET "/transcanno/transcribe/display_page?page_id=1" for 10.12.59.0 at 2017-12-04 14:59:19 +0000
I, [2017-12-04T14:59:19.754786 #24]  INFO -- : Processing by TranscribeController#display_page as HTML
I, [2017-12-04T14:59:19.754857 #24]  INFO -- :   Parameters: {"page_id"=>"1"}
D, [2017-12-04T14:59:19.756260 #24] DEBUG -- :   Page Load (0.7ms)  SELECT  `pages`.* FROM `pages`  WHERE `pages`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:19.757709 #24] DEBUG -- :   Work Load (0.8ms)  SELECT  `works`.* FROM `works`  WHERE `works`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:19.758856 #24] DEBUG -- :   Collection Load (0.6ms)  SELECT  `collections`.* FROM `collections`  WHERE `collections`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:19.760010 #24] DEBUG -- :   IaWork Load (0.6ms)  SELECT  `ia_works`.* FROM `ia_works`  WHERE `ia_works`.`work_id` = 1 LIMIT 1
D, [2017-12-04T14:59:19.761110 #24] DEBUG -- :    (0.6ms)  SELECT COUNT(*) FROM `interactions`
D, [2017-12-04T14:59:19.762589 #24] DEBUG -- :   User Load (0.6ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
D, [2017-12-04T14:59:19.763542 #24] DEBUG -- :    (0.4ms)  BEGIN
D, [2017-12-04T14:59:19.764973 #24] DEBUG -- :   SQL (0.6ms)  INSERT INTO `interactions` (`action`, `browser`, `collection_id`, `created_on`, `ip_address`, `page_id`, `params`, `session_id`, `status`, `user_id`, `work_id`) VALUES ('display_page', 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', 1, '2017-12-04 14:59:19', '10.12.59.0', 1, '{\"page_id\"=>\"1\", \"controller\"=>\"transcribe\", \"action\"=>\"display_page\"}', 142, 'incomplete', 2, 1)
D, [2017-12-04T14:59:19.777364 #24] DEBUG -- :    (12.1ms)  COMMIT
D, [2017-12-04T14:59:19.778280 #24] DEBUG -- :   PageBlock Load (0.5ms)  SELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'transcribe' AND `page_blocks`.`view` = 'display_page'
D, [2017-12-04T14:59:19.779259 #24] DEBUG -- :    (0.6ms)  SELECT categories.title, categorystyles.colour, categorystyles.textdecoration, categorystyles.fontstyle, categories.id FROM `categorystyles` INNER JOIN `categories` ON `categories`.`id` = `categorystyles`.`category_id`
I, [2017-12-04T14:59:19.779652 #24]  INFO -- : Completed 500 Internal Server Error in 25ms
F, [2017-12-04T14:59:19.781058 #24] FATAL -- : 
Errno::ENOENT (No such file or directory @ rb_sysopen - app/assets/javascripts/medium-tag-styles.css):
  app/controllers/category_controller.rb:657:in `write'
  app/controllers/category_controller.rb:657:in `apply_all_styles_h'
  app/controllers/collection_controller.rb:49:in `updateStylesIfCollectionIdNotInCookies'
  app/controllers/transcribe_controller.rb:18:in `display_page'
```

http://kommul.eurac.edu/transcanno/page_version/list?page_id=1
```
I, [2017-12-04T14:59:53.753814 #24]  INFO -- : Started GET "/transcanno/page_version/list?page_id=1" for 10.12.59.0 at 2017-12-04 14:59:53 +0000
I, [2017-12-04T14:59:53.755438 #24]  INFO -- : Processing by PageVersionController#list as HTML
I, [2017-12-04T14:59:53.755489 #24]  INFO -- :   Parameters: {"page_id"=>"1"}
D, [2017-12-04T14:59:53.756819 #24] DEBUG -- :   Page Load (0.7ms)  SELECT  `pages`.* FROM `pages`  WHERE `pages`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:53.758083 #24] DEBUG -- :   Work Load (0.6ms)  SELECT  `works`.* FROM `works`  WHERE `works`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:53.759062 #24] DEBUG -- :   Collection Load (0.5ms)  SELECT  `collections`.* FROM `collections`  WHERE `collections`.`id` = 1 LIMIT 1
D, [2017-12-04T14:59:53.760114 #24] DEBUG -- :   IaWork Load (0.5ms)  SELECT  `ia_works`.* FROM `ia_works`  WHERE `ia_works`.`work_id` = 1 LIMIT 1
D, [2017-12-04T14:59:53.761095 #24] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM `interactions`
D, [2017-12-04T14:59:53.762534 #24] DEBUG -- :   User Load (0.5ms)  SELECT  `users`.* FROM `users`  WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
D, [2017-12-04T14:59:53.763402 #24] DEBUG -- :    (0.4ms)  BEGIN
D, [2017-12-04T14:59:53.764740 #24] DEBUG -- :   SQL (0.5ms)  INSERT INTO `interactions` (`action`, `browser`, `collection_id`, `created_on`, `ip_address`, `page_id`, `params`, `session_id`, `status`, `user_id`, `work_id`) VALUES ('list', 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0', 1, '2017-12-04 14:59:53', '10.12.59.0', 1, '{\"page_id\"=>\"1\", \"controller\"=>\"page_version\", \"action\"=>\"list\"}', 143, 'incomplete', 2, 1)
D, [2017-12-04T14:59:53.775844 #24] DEBUG -- :    (10.8ms)  COMMIT
D, [2017-12-04T14:59:53.776889 #24] DEBUG -- :   PageBlock Load (0.6ms)  SELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'page_version' AND `page_blocks`.`view` = 'list'
D, [2017-12-04T14:59:53.778307 #24] DEBUG -- :   PageVersion Load (0.5ms)  SELECT  `page_versions`.* FROM `page_versions`  WHERE `page_versions`.`page_id` = 1  ORDER BY page_version DESC LIMIT 1
I, [2017-12-04T14:59:53.778653 #24]  INFO -- : Completed 500 Internal Server Error in 23ms
F, [2017-12-04T14:59:53.779939 #24] FATAL -- : 
NoMethodError (undefined method `prev' for nil:NilClass):
  app/controllers/page_version_controller.rb:7:in `set_versions'
```

**Comment by iiegn** [comment]
...also: you could try to **temporarily** make `/log` somehow serve the log files - then, you could have a quicker debug-loop.

**Comment by iiegn** [comment]
closing this here.
has been moved to https://gitlab.inf.unibz.it/commul/docker/transcanno/issues/3
